# Generated by Django 5.1.4 on 2024-12-28 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostique', models.TextField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('nss', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=35, null=True)),
                ('mutuelle', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestiondpi.consultation')),
                ('description', models.TextField(blank=True, null=True)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestiondpi.consultation')),
                ('description', models.TextField(blank=True, null=True)),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('role', models.CharField(choices=[('medecin', 'Medecin'), ('administratif', 'Administratif'), ('infirmier', 'Infirmier'), ('radiologue', 'radiologue'), ('pharmacien', 'Pharmacien'), ('laboratorien', 'Laboratorien')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=35, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hopital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.hopital')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='gestiondpi.employe'),
        ),
        migrations.CreateModel(
            name='Ordonance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='ordonance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.ordonance'),
        ),
        migrations.CreateModel(
            name='OrdonanceMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField()),
                ('duree', models.IntegerField(help_text='Duration in days')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.medicament')),
                ('ordonance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.ordonance')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationOutil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.consultation')),
                ('outil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.outil')),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestiondpi.patient')),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.patient'),
        ),
        migrations.CreateModel(
            name='BilanBioTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('choice1', 'Choice1'), ('choice3', 'Choice2'), ('ext...', 'Ext..')], max_length=20)),
                ('valeur', models.FloatField()),
                ('bilan_biologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.bilanbiologique')),
            ],
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe'),
        ),
        migrations.CreateModel(
            name='ImageRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('bilan_radiologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.bilanradiologique')),
            ],
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe'),
        ),
        migrations.CreateModel(
            name='SoinMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.medicament')),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.soin')),
            ],
        ),
        migrations.CreateModel(
            name='SoinInfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe')),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.soin')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe')),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.soin')),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestiondpi.consultation')),
                ('description', models.TextField(blank=True, null=True)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(auto_now=True)),
                ('laborantin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('bilan_radiologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.bilanradiologique')),
            ],
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.patient'),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe'),
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='gestiondpi.employe')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.patient')),
            ],
            options={
                'unique_together': {('patient', 'medecin')},
            },
        ),
        migrations.CreateModel(
            name='BilanBioTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cholesterol', 'Cholestérol'), ('fer', 'Fer Tests'), ('hypertension', 'Hypertension')], max_length=20)),
                ('valeur', models.FloatField()),
                ('bilan_biologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.bilanbiologique')),
            ],
            options={
                'unique_together': {('bilan_biologique', 'type')},
            },
        ),
    ]
