# Generated by Django 5.1.4 on 2024-12-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonance',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
