# Generated by Django 5.1.4 on 2024-12-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
