# Generated by Django 5.1.4 on 2025-01-04 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondpi.employe'),
        ),
    ]
