# Generated by Django 5.1.4 on 2024-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('medecin', 'Medecin'), ('administratif', 'Administratif'), ('infirmier', 'Infirmier'), ('radiologue', 'radiologue'), ('pharmacien', 'Pharmacien'), ('laboratorien', 'Laboratorien')], max_length=20),
        ),
    ]
