#<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-31 11:16
#=======
# Generated by Django 5.1.4 on 2024-12-31 23:11
#>>>>>>> 1307781ea59976550b0e74b287ee2aab8dc45181

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0002_ordonance_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='stock',
        ),
    ]
