# Generated by Django 5.1.4 on 2024-12-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0002_ordonance_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='stock',
        ),
    ]
