# Generated by Django 5.1.4 on 2025-01-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0003_remove_medicament_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilanradiologique',
            old_name='created_at',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='bilanradiologique',
            old_name='updated_at',
            new_name='date_fin',
        ),
    ]
