# Generated by Django 5.1.4 on 2025-01-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0004_rename_created_at_bilanradiologique_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonancemedicament',
            name='medicament',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='soinmedicament',
            name='medicament',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
    ]
