# Generated by Django 5.1.4 on 2025-01-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0005_alter_ordonancemedicament_medicament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='diagnostique',
        ),
    ]
