# Generated by Django 5.1.4 on 2025-01-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0006_remove_consultation_diagnostique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonance',
            name='date',
        ),
    ]
