# Generated by Django 5.1.4 on 2025-01-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0007_remove_ordonance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonancemedicament',
            name='dose',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordonancemedicament',
            name='duree',
            field=models.CharField(max_length=100),
        ),
    ]
