from django.contrib import admin
from .models import Hopital, Employe, Patient, Ordonance, Consultation, BilanBiologique, BilanRadiologique, Outil, ConsultationOutil, BilanBioTest, Medicament, OrdonanceMedicament, ImageRadio, Soin, SoinMedicament, SoinInfirmier, ObservationEtat, Traitement

admin.site.register(Hopital)
admin.site.register(Employe)
admin.site.register(Patient)
admin.site.register(Ordonance)
admin.site.register(Consultation)
admin.site.register(BilanBiologique)
admin.site.register(BilanRadiologique)
admin.site.register(Outil)
admin.site.register(ConsultationOutil)
admin.site.register(BilanBioTest)
admin.site.register(Medicament)
admin.site.register(OrdonanceMedicament)
admin.site.register(ImageRadio)
admin.site.register(Soin)
admin.site.register(SoinMedicament)
admin.site.register(SoinInfirmier)
admin.site.register(ObservationEtat)
admin.site.register(Traitement)
